### ISSUE TITLE
$ ./manage.py add_project: error: too few arguments

### ISSUE THREAD

**Issue by huangk3** [macarthur-lab/seqr#230]
Hi all,

I got the following error when I tried to load the 1kg project following the instructions in https://github.com/macarthur-lab/seqr/blob/master/deploy/mac_osx/README.md

(seqr) [Thu Apr 27 08:53:13 huangk3@ai-cgsdev4:~/Software/seqr/code/seqr ] $ ./manage.py add_project 1kg
ERROR: column base_project.project_status does not exist
LINE 1: ...ct"."project_name", "base_project"."description", "base_proj...
                                                             ^
usage: manage.py add_project [-h] [--version] [-v {0,1,2,3}]
                             [--settings SETTINGS] [--pythonpath PYTHONPATH]
                             [--traceback] [--no-color]
                             project_id project_name
manage.py add_project: error: too few arguments

The add_project command needs two arguments but there is only one in the instruction. Does anybody know what kind of "project_id" and "project_name" parameter should I give for the 1kg project?

As for the "column base_project.project_status does not exist" error, I checked  the “base_project” table in the postgresql database, I didn’t find the “project_status” column. Instead, a “status” column is there. I suppose the error may be caused by typo:
seqrdb=# select * from base_project;
 id | project_id | project_name | description | is_public | created_date | last_accessed_date | category | **status** | default_control_cohort 
----+------------+--------------+-------------+-----------+--------------+--------------------+----------+--------+------------------------
(0 rows)

Could anybody please help? Thanks

**Comment by bw2** [comment]
@huangk3 
if you `git pull` the latest code from master, this issue should now be fixed.

**Comment by bw2** [comment]
For the migration error, 

could you please try running 
```
python manage.py makemigrations
python manage.py migrate?
```

**Comment by bw2** [comment]
Also, if you're starting a new installation, you might want try the new Kubernetes-based deployment
https://github.com/macarthur-lab/seqr/blob/master/deploy/kubernetes/README.md

**Comment by huangk3** [comment]
Hi @bw2, I tried the protocol as suggested above. The issues are still there. My OS is Red Hat EL7. Can that be a problem? Thanks.

**[Fri Apr 28 08:35:57 huangk3@ai-cgsdev4:~/Software/seqr/code/seqr ] $ git pull**
remote: Counting objects: 245, done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 245 (delta 161), reused 199 (delta 117), pack-reused 0
Receiving objects: 100% (245/245), 29.86 KiB | 0 bytes/s, done.
Resolving deltas: 100% (161/161), completed with 63 local objects.
From https://github.com/macarthur-lab/seqr
   40dff41..cf3472a  master     -> origin/master
Updating 40dff41..cf3472a
Fast-forward
 .gitignore                                                                                     |   1 +
 deploy/README.md                                                                               |   2 +-
 deploy/docker/matchbox/Dockerfile                                                              |   9 +-
 deploy/docker/matchbox/application.properties                                                  |  13 --
 deploy/docker/matchbox/bashrc                                                                  |  13 ++
 deploy/docker/matchbox/entrypoint.sh                                                           |   7 +-
 deploy/docker/mongo/Dockerfile                                                                 |   6 +
 deploy/docker/mongo/bashrc                                                                     |  13 ++
 deploy/docker/phenotips/Dockerfile                                                             |   7 +
 deploy/docker/phenotips/bashrc                                                                 |  21 +++
 deploy/docker/postgres/gcloud/000_init.sh                                                      |  11 ++
 deploy/docker/postgres/gcloud/Dockerfile                                                       |   8 +-
 deploy/docker/postgres/local/{002_init.sh => 000_init.sh}                                      |   2 +-
 deploy/docker/postgres/local/Dockerfile                                                        |  11 +-
 deploy/docker/postgres/local/bashrc                                                            |   2 +
 deploy/docker/seqr/gcloud/Dockerfile                                                           |  18 +--
 deploy/docker/seqr/gcloud/bashrc                                                               |   2 +
 deploy/docker/seqr/local/Dockerfile                                                            |  20 +--
 deploy/docker/seqr/local/bashrc                                                                |   2 +
 deploy/docker/seqr/local/entrypoint.sh                                                         |   4 -
 deploy/kubernetes/config/gcloud-settings.yaml                                                  |   4 +-
 deploy/kubernetes/scripts/deploy_matchbox.sh                                                   |   4 +-
 deploy/kubernetes/scripts/deploy_seqr.sh                                                       |   6 +-
 deploy/kubernetes/secrets/gcloud/matchbox/application.properties                               |  12 +-
 deploy/kubernetes/secrets/gcloud/postgres/postgres.password                                    |   2 +-
 deploy/kubernetes/secrets/local/matchbox/application.properties                                |  12 +-
 deploy/kubernetes/templates/matchbox/matchbox-deployment.local.yaml                            |  32 ----
 .../templates/matchbox/{matchbox-deployment.gcloud.yaml => matchbox-deployment.yaml}           |   8 +-
 deploy/kubernetes/utils/deploy_utils.py                                                        |   2 +-
 deploy/kubernetes/utils/seqrctl_utils.py                                                       |  15 +-
 deploy/mac_osx/README.md                                                                       |   2 +-
 seqr/management/commands/combine_transfered_projects.py                                        |  16 +-
 seqr/management/commands/{list_datasets.py => list_sample_batches.py}                          |  12 +-
 seqr/management/commands/update_projects_in_new_schema.py                                      |   6 +-
 seqr/models.py                                                                                 |   2 +-
 seqr/urls.py                                                                                   |  17 ++-
 seqr/views/apis/awesomebar_api.py                                                              |   4 +-
 seqr/views/apis/phenotips_api_tests.py                                                         |   3 -
 seqr/views/apis/project_api_tests.py                                                           |  22 ++-
 seqr/views/pages/dashboard_page.py                                                             |  22 ++-
 seqr/views/pages/dashboard_page_tests.py                                                       |   1 -
 seqr/views/pages/project_page.py                                                               | 381 +++++++++++++++++++++++++++++++++++++++++++++++
 seqr/views/pages/project_page_tests.py                                                         |  40 +++++
 seqr/views/pages/staff/case_review_page.py                                                     |   2 +-
 settings.py                                                                                    |   3 +-
 xbrowse/core/genomeloc.py                                                                      |   6 +-
 xbrowse/datastore/mongo_datastore.py                                                           |   2 +-
 xbrowse_server/api/views.py                                                                    |   8 +
 xbrowse_server/base/management/commands/add_project.py                                         |  10 +-
 xbrowse_server/base/management/commands/load_reference.py                                      |   6 -
 xbrowse_server/base/management/commands/load_resources.py                                      |   6 -
 xbrowse_server/base/migrations/0003_auto_20160526_0022.py                                      |  10 +-
 xbrowse_server/base/migrations/0019_auto_20170426_0348.py                                      |  20 +++
 xbrowse_server/phenotips/reporting_utilities.py                                                |   5 +-
 xbrowse_server/templates/base.html                                                             |   2 +-
 xbrowse_server/templates/matchmaker/matchbox_dashboard.html                                    |  12 +-
 56 files changed, 692 insertions(+), 197 deletions(-)
 delete mode 100644 deploy/docker/matchbox/application.properties
 create mode 100644 deploy/docker/matchbox/bashrc
 create mode 100644 deploy/docker/mongo/bashrc
 create mode 100644 deploy/docker/phenotips/bashrc
 create mode 100755 deploy/docker/postgres/gcloud/000_init.sh
 rename deploy/docker/postgres/local/{002_init.sh => 000_init.sh} (88%)
 delete mode 100644 deploy/kubernetes/templates/matchbox/matchbox-deployment.local.yaml
 rename deploy/kubernetes/templates/matchbox/{matchbox-deployment.gcloud.yaml => matchbox-deployment.yaml} (91%)
 rename seqr/management/commands/{list_datasets.py => list_sample_batches.py} (56%)
 create mode 100644 seqr/views/pages/project_page.py
 create mode 100644 seqr/views/pages/project_page_tests.py
 create mode 100644 xbrowse_server/base/migrations/0019_auto_20170426_0348.py

**(seqr) [Fri Apr 28 08:42:53 huangk3@ai-cgsdev4:~/Software/seqr/code/seqr ] $ ./manage.py makemigrations**
ERROR: column base_project.project_status does not exist
LINE 1: ...ct"."project_name", "base_project"."description", "base_proj...
                                                             ^
No changes detected

**(seqr) [Fri Apr 28 08:43:40 huangk3@ai-cgsdev4:~/Software/seqr/code/seqr ] $ ./manage.py migrate**
ERROR: column base_project.project_status does not exist
LINE 1: ...ct"."project_name", "base_project"."description", "base_proj...
                                                             ^
Operations to perform:
  Apply all migrations: admin, auth, base, breakpoint_search, contenttypes, gene_lists, guardian, reference_data, seqr, sessions
Running migrations:
  Applying base.0019_auto_20170426_0348...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 215, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 513, in alter_field
    old_db_params, new_db_params, strict)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/backends/postgresql/schema.py", line 112, in _alter_field
    new_db_params, strict,
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 703, in _alter_field
    self.execute(self._create_unique_sql(model, [new_field.column]))
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 119, in execute
    cursor.execute(sql, params)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/nethome/huangk3/.virtualenvs/seqr/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "guid" named in key does not exist 



I'm trying the Kubernetes-based deployment, but seems it's for MacOSX, is it possible to built it on Red Hat EL7 or AWS? If so, is there any best practice I can refer to? Thank you very much.

**Comment by bw2** [comment]
@huangk3 if your current seqr database is empty or doesn't have any data that you'd like to keep, it might be easiest to delete and re-create the database. 
If you do have data, there are some trouble-shooting steps here
https://simpleisbetterthancomplex.com/tutorial/2016/07/26/how-to-reset-migrations.html

Also, Kubernetes does run on linux and AWS. Though I've only tested on MacOSX and Google cloud, there are instructions for AWS at
https://kubernetes.io/docs/getting-started-guides/aws/
