### ISSUE TITLE
Seqr deploy failing with npm

### ISSUE THREAD

**Issue by jules-o** [macarthur-lab/seqr#536]
I'm new to linux and kubernetes so this might be something I'm doing wrong rather than a bug.
Installing seqr on Ubuntu 18.04.1, VM=VirtualBox. All goes fine until deploying seqr pod, then throws first a lot of warnings about syntax error and deprecated packages, then fails with the error below.
I've updated npm and node as per the warnings but it makes no difference. I can't work out what else I should be doing... help?

------------------------------------------------
semantic-ui@2.2.12 install /node_modules/semantic-ui
gulp install

[14:40:11] Using gulpfile /node_modules/semantic-ui/gulpfile.js
[14:40:11] Starting 'install'...

[14:40:11] Starting 'run setup'...
? Set-up Semantic UI (Use arrow keys)
❯ Automatic (Use default locations and all components) 
  Express (Set components and output folder) 
  Custom (Customize all src/dist values) [14:40:11] 'run setup' errored after 30 ms
[14:40:11] SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
    at new RegExp (<anonymous>)
    at breakLines (/node_modules/gulp-prompt/node_modules/inquirer/lib/utils/screen-manager.js:108:15)
    at module.exports.ScreenManager.render (/node_modules/gulp-prompt/node_modules/inquirer/lib/utils/screen-manager.js:55:22)
    at Prompt.render (/node_modules/gulp-prompt/node_modules/inquirer/lib/prompts/list.js:103:15)
    at Prompt._run (/node_modules/gulp-prompt/node_modules/inquirer/lib/prompts/list.js:74:8)
    at Prompt.run (/node_modules/gulp-prompt/node_modules/inquirer/lib/prompts/base.js:57:8)
    at Object.<anonymous> (/node_modules/gulp-prompt/node_modules/inquirer/lib/ui/prompt.js:84:12)
    at module.exports (/node_modules/gulp-prompt/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/node_modules/gulp-prompt/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/node_modules/gulp-prompt/node_modules/rx-lite/rx.lite.js:63:31)
[14:40:11] 'install' errored after 34 ms
[14:40:11] SyntaxError in plugin "run-sequence(run setup)"
Message:
    Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
Stack:
SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
    at new RegExp (<anonymous>)
    at breakLines (/node_modules/gulp-prompt/node_modules/inquirer/lib/utils/screen-manager.js:108:15)
    at module.exports.ScreenManager.render (/node_modules/gulp-prompt/node_modules/inquirer/lib/utils/screen-manager.js:55:22)
    at Prompt.render (/node_modules/gulp-prompt/node_modules/inquirer/lib/prompts/list.js:103:15)
    at Prompt._run (/node_modules/gulp-prompt/node_modules/inquirer/lib/prompts/list.js:74:8)
    at Prompt.run (/node_modules/gulp-prompt/node_modules/inquirer/lib/prompts/base.js:57:8)
    at Object.<anonymous> (/node_modules/gulp-prompt/node_modules/inquirer/lib/ui/prompt.js:84:12)
    at module.exports (/node_modules/gulp-prompt/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/node_modules/gulp-prompt/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/node_modules/gulp-prompt/node_modules/rx-lite/rx.lite.js:63:31)

? Set-up Semantic UI Automatic (Use default locations and all components)

readline.js:1020
            throw err;
            ^

SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
    at new RegExp (<anonymous>)
    at breakLines (/node_modules/gulp-prompt/node_modules/inquirer/lib/utils/screen-manager.js:108:15)
    at module.exports.ScreenManager.render (/node_modules/gulp-prompt/node_modules/inquirer/lib/utils/screen-manager.js:55:22)
    at Prompt.render (/node_modules/gulp-prompt/node_modules/inquirer/lib/prompts/list.js:103:15)
    at Prompt.onSubmit (/node_modules/gulp-prompt/node_modules/inquirer/lib/prompts/list.js:116:8)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/node_modules/gulp-prompt/node_modules/rx-lite/rx.lite.js:1535:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/node_modules/gulp-prompt/node_modules/rx-lite/rx.lite.js:1469:31)
    at AnonymousObserver.tryCatcher (/node_modules/gulp-prompt/node_modules/rx-lite/rx.lite.js:63:31)
    at AutoDetachObserverPrototype.next (/node_modules/gulp-prompt/node_modules/rx-lite/rx.lite.js:5782:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/node_modules/gulp-prompt/node_modules/rx-lite/rx.lite.js:1469:31)
npm WARN seqr@0.2.0 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.2.12 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.2.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-10T14_40_16_763Z-debug.log
The command '/bin/sh -c wget -N https://raw.githubusercontent.com/macarthur-lab/seqr/master/ui/package.json    && alias node=nodejs    && ./install_npm_packages.sh    && npm install -g npm-check-updates' returned a non-zero code: 1

**Comment by bw2** [comment]
hi Jules, just to double check, what version of node and npm are you using?
I have
$ node --version
v10.6.0
$ npm --version
6.2.0

**Comment by bw2** [comment]
I see.. and are you using minikube, or installing directly on the VirtualBox VM?

**Comment by jules-o** [comment]
Minikube. I'm following the "Kubernetes-based Installation Instructions", but just removed the --vm-driver=xhyve flag from start_minikube.sh. 

I don't know if it's relevant but I also had to copy install_npm_packages.sh from ui/shared to deploy/docker/seqr/shared, else I got a "no such file or directory".

**Comment by jules-o** [comment]
Sorry if I'm being stupid - like I said I'm new to linux and kubernetes - I'm normally quite good at figuring out solutions but I don't even know where to start with this one.

**Comment by bw2** [comment]
Hi Jules, strangely, this may be related to drive mounting issues which I haven't been able to track down. 
I just merged a number of minikube deployment fixes to the `dev` branch - one of which is to disable drive mounting and just clone the seqr repo from github. 
If you could switch to `dev` and re-deploy just seqr (`./servctl deploy -d seqr minikube`) 
or, if you'd like, all components (`./servctl deploy-all minikube`), you should then be able to build the ui. 
Another option, if you don't want to get into minikube/kubernetes, is to use the Dockerfiles as install instructions, and deploy components manually.

**Comment by jules-o** [comment]
Thanks bw2, glad it's not just me! I suspect deploying manually might be beyond my skill...
Deploying seqr from dev does get past the npm errors and starts the pod running, but then it stops with is_ready status = false. Pod log shows all the updates, copying etc, but then ends with:

236 static files copied to '/seqr/static'.
+ cd /seqr_settings
+ gunicorn -w 4 -c gunicorn_config.py wsgi:application
+ echo '*:*:*:*:devpassword'
+ chmod 600 /root/.pgpass
+ stdbuf -o0 grep -v curl
+ tee /var/log/gunicorn.log
+ sleep 1000000000000
/entrypoint.sh: line 51: gunicorn: command not found

What am I missing?

**Comment by bw2** [comment]
hi Jules, that's a bug with the gunicorn install. 
If you update dev and run `./servctl deploy seqr minikube` it should be fixed now.

**Comment by jules-o** [comment]
Aha! Now it got all the way up to pipeline-runner - then:
```
2018-08-17 19:38:56,153 INFO     pipeline-runner is_running status = Running
2018-08-17 19:38:56,427 INFO     ==> kubectl exec  pipeline-runner-66584db49c-7dcrd -- python2.7 -u manage.py update_all_reference_data --omim-key '$OMIM_KEY'
2018-08-17 19:38:58,519 INFO     Unknown command: 'update_all_reference_data'
2018-08-17 19:38:58,520 INFO     Type 'manage.py help' for usage.
2018-08-17 19:38:59,136 INFO     command terminated with exit code 1
Traceback (most recent call last):
  File "./servctl", line 255, in <module>
    update_reference_data(args.deployment_target)
  File "/home/flutabex/seqr/deploy/utils/loading_utils.py", line 117, in update_reference_data
    run_in_pod(pod_name, "python2.7 -u manage.py update_all_reference_data --omim-key '$OMIM_KEY'" % locals(), verbose=True, print_command=True)
  File "/home/flutabex/seqr/deploy/utils/kubectl_utils.py", line 133, in run_in_pod
    run("kubectl exec %(it_arg)s %(full_pod_name)s -- %(command)s" % locals(), errors_to_ignore=errors_to_ignore, print_command=print_command, verbose=verbose, is_interactive=is_interactive)
  File "/home/flutabex/seqr/seqr/utils/shell_utils.py", line 81, in run
    raise RuntimeError(output)
RuntimeError: Unknown command: 'update_all_reference_data'
Type 'manage.py help' for usage.
command terminated with exit code 1
```
Feels like I'm so close...

**Comment by hanars** [comment]
Have you tried running `python manage.py load_resources`

**Comment by jules-o** [comment]
Hi hanars, Yep - if I run it inside either container I get:
```
pipeline-runner-bdff4b8f9-cr9bx:/seqr]$ python manage.py load_resources
2018-08-17 19:39:29,047 WARNING:  WARNING: get_reference().get_gene_symbols(): gene_symbols collection not found in mongodb. If this is a new install, please run python manage.py load_resources
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/seqr/xbrowse_server/base/management/commands/load_resources.py", line 6, in handle
    get_reference().load()
  File "/seqr/xbrowse/reference/reference.py", line 76, in load
    self._load_clinvar()
  File "/seqr/xbrowse/reference/reference.py", line 147, in _load_clinvar
    chunk = list(itertools.islice(iterator, 0, 1000))
  File "/seqr/xbrowse/reference/clinvar.py", line 20, in parse_clinvar_vcf
    clinvar_vcf_path = settings.REFERENCE_SETTINGS.clinvar_vcf_file
AttributeError: 'module' object has no attribute 'clinvar_vcf_file'
```
Or from outside:
```
flutabex@Fred:~/seqr$ python manage.py load_resources
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/flutabex/seqr/settings.py", line 418, in <module>
    from local_settings import *
ImportError: No module named local_settings
```
I also tried copying all the _settings files up to the main seqr directory alongside manage.py (just in case) but it definitely didn't like that.

**Comment by bw2** [comment]
also, that update_all_reference_data script is on `dev` so for now, if you could do
```
./servctl shell seqr minikube
git checkout dev
python manage.py makemigrations
python manage.py update_all_reference_data
```

**Comment by jules-o** [comment]
Oops, posts crossed - just trying inside seqr shell - do I use --omim-key or --skip-omim?

**Comment by jules-o** [comment]
So: using the seqr-secrets omim_key (taken from Dashboard) gives:
```
seqr-8d76df76d-jnl5b:/seqr]$ git checkout dev
Already on 'dev'
Your branch is up-to-date with 'origin/dev'.
seqr-8d76df76d-jnl5b:/seqr]$ python manage.py makemigrations
2018-08-17 21:54:44,678 WARNING:  WARNING: get_reference().get_gene_symbols(): gene_symbols collection not found in mongodb. If this is a new install, please run python manage.py load_resources
No changes detected
seqr-8d76df76d-jnl5b:/seqr]$ python manage.py update_all_reference_data --omim-key b21pbS1rZXktcGxhY2Vob2xkZXI=
2018-08-17 21:55:33,520 WARNING:  WARNING: get_reference().get_gene_symbols(): gene_symbols collection not found in mongodb. If this is a new install, please run python manage.py load_resources
2018-08-17 21:55:34,580 INFO:  Re-using /tmp/gencode.v19.annotation.gtf.gz previously downloaded from ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/seqr/reference_data/management/commands/update_all_reference_data.py", line 30, in handle
    update_gencode(19, reset=True)
  File "/seqr/reference_data/management/commands/update_gencode.py", line 75, in update_gencode
    logger.info("Dropping the {} existing TranscriptInfo entries".format(TranscriptInfo.objects.count()))
  File "/root/.local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/django/db/models/query.py", line 363, in count
    return self.query.get_count(using=self.db)
  File "/root/.local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 498, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/root/.local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 479, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/root/.local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/root/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "reference_data_transcriptinfo" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "reference_data_transcript...
```

**Comment by bw2** [comment]
Ah sorry I meant `python manage.py migrate` instead of makemigrations

**Comment by jules-o** [comment]
Lol d'oh! Thanks, seems to be doing its thing now. Will have to leave it overnight as late here, fingers crossed...

**Comment by jules-o** [comment]
Hello again, 

This is probably a *really* stupid question, but: pipeline-runner has completed - what do I do now?

I've got:
```
2018-08-19 11:44:37,569 INFO     [I 06:27:43.316 NotebookApp] The Jupyter Notebook is running at:
2018-08-19 11:44:37,569 INFO     [I 06:27:43.316 NotebookApp] http://(pipeline-runner-5f59fd4cdf-5szvm or 127.0.0.1):30005/
2018-08-19 11:44:37,569 INFO     [I 06:27:43.316 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
2018-08-19 11:44:37,569 INFO     [W 06:27:43.317 NotebookApp] No web browser found: could not locate runnable browser.
```
and can access NotebookApp by going to the url in my browser.

I tried ```./servctl load-example-project -g 38 minikube``` but must be missing an argument because it stops at: 
```
2018-08-19 19:00:26,820 INFO     ==> kubectl exec  pipeline-runner-5868c4c8f8-2snkf -- 
        cd /hail-elasticsearch-pipelines/;         python2.7 ./gcloud_dataproc/submit.py             --run-locally hail_scripts/v01/load_dataset_to_es.py             --genome-version 38             --project-guid 1kg             --sample-type WES             --dataset-type VARIANTS             --host elasticsearch             --vep-block-size 30             https://storage.googleapis.com/seqr-public/test-projects/1kg-exomes/1kg.liftover.GRCh38.vep.vcf.gz
        
2018-08-19 19:00:26,879 INFO     error: expected 'exec POD_NAME COMMAND [ARG1] [ARG2] ... [ARGN]'.
2018-08-19 19:00:26,879 INFO     POD_NAME and COMMAND are required arguments for the exec command
2018-08-19 19:00:26,879 INFO     See 'kubectl exec -h' for help and examples.
2018-08-19 19:00:26,880 INFO     /bin/sh: 2: cd: can't cd to /hail-elasticsearch-pipelines/
2018-08-19 19:00:26,887 INFO     python2.7: can't open file './gcloud_dataproc/submit.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./servctl", line 277, in <module>
    load_example_project(args.deployment_target, genome_version=args.genome_version)
  File "/home/flutabex/seqr/deploy/utils/loading_utils.py", line 99, in load_example_project
    ped=ped)
  File "/home/flutabex/seqr/deploy/utils/loading_utils.py", line 64, in load_project
    """ % locals(), verbose=True)
  File "/home/flutabex/seqr/deploy/utils/kubectl_utils.py", line 133, in run_in_pod
    run("kubectl exec %(it_arg)s %(full_pod_name)s -- %(command)s" % locals(), errors_to_ignore=errors_to_ignore, print_command=print_command, verbose=verbose, is_interactive=is_interactive)
  File "/home/flutabex/seqr/seqr/utils/shell_utils.py", line 81, in run
    raise RuntimeError(output)
RuntimeError: error: expected 'exec POD_NAME COMMAND [ARG1] [ARG2] ... [ARGN]'.
POD_NAME and COMMAND are required arguments for the exec command
See 'kubectl exec -h' for help and examples.
/bin/sh: 2: cd: can't cd to /hail-elasticsearch-pipelines/
python2.7: can't open file './gcloud_dataproc/submit.py': [Errno 2] No such file or directory
```

Also still getting a lot of the "gene_symbols not found in mongodb" warnings if that's relevant. Running ```python manage.py load_resources``` inside the shell fails as before with:
```
seqr-5944969bff-c5nsc:/seqr]$ python manage.py load_resources
2018-08-18 20:14:16,192 WARNING:  WARNING: get_reference().get_gene_symbols(): gene_symbols collection not found in mongodb. If this is a new install, please run python manage.py load_resources
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/seqr/xbrowse_server/base/management/commands/load_resources.py", line 6, in handle
    get_reference().load()
  File "/seqr/xbrowse/reference/reference.py", line 76, in load
    self._load_clinvar()
  File "/seqr/xbrowse/reference/reference.py", line 147, in _load_clinvar
    chunk = list(itertools.islice(iterator, 0, 1000))
  File "/seqr/xbrowse/reference/clinvar.py", line 20, in parse_clinvar_vcf
    clinvar_vcf_path = settings.REFERENCE_SETTINGS.clinvar_vcf_file
AttributeError: 'module' object has no attribute 'clinvar_vcf_file'
```

**Comment by jules-o** [comment]
P.S. Sorry to keep bothering you. I've been trying for months to find a way to analyse my own WGS due to severe health problems, and have found that all the other open source tools are either too user-unfriendly, or can't handle my files, or only work with GRCh37 - and I have GRCh38. Seqr was recommended as the best so I'd really like to make it work, but it's a very steep learning curve since my knowledge is all on the medical genetics side rather than bioinformatics.

**Comment by bw2** [comment]
Hi Jules, thanks for the patience in working through these issues.. I will post detailed steps after another set of updates.

**Comment by jules-o** [comment]
Thanks bw2, glad it's not just me being thick!

**Comment by bw2** [comment]
Hi Jules, I've updated the installation docs in the main README for local MacOS or linux installations
(https://github.com/macarthur-lab/seqr/blob/master/README.md)
If you can update your local version from master, and run through the 3 install steps, it will load an example project. A similar command can then be used to load your own data.

**Comment by jules-o** [comment]
Hi bw2,

THANK YOU!! (it's working)

Only... when I try to use my own file, hail says ```"message" : "service-account@upheld-rookery-214823.iam.gserviceaccount.com does not have storage.buckets.get access to seqr-reference-data."```

Been trying to look it up but not getting anywhere - is that something I can change for myself?

**Comment by bw2** [comment]
There's a google account key in `deploy/secrets/shared/gcloud/service-account-key.json`
which google tools need to access google storage buckets (even if they're public - like gs://seqr-reference-data).
I committed a key from a temp google account to deploy/secrets/shared/gcloud/service-account-key.json, but it's not working for some reason. 

If you could go through these steps and replace service-account-key.json with your own (from whatever google account)

# Go to https://console.developers.google.com/apis/credentials
#  In the "Create credentials" drop-down, select "Service account key"
#  Select "Compute Engine default service account" and Key type "JSON"
#  Download the .json file and copy it to  deploy/secrets/shared/gcloud/service-account-key.json

You can then apply it by running 
```
./servctl deploy secrets minikube
./servctl deploy -d pipeline-runner minikube
```

**Comment by jules-o** [comment]
Hi bw2, thanks and sorry for slow reply - computer troubles.

Turns out a line was missing from the README minikube example - ```load-example-project``` worked but trying to load my own data threw the same error. Checking against loading_utils.py found README is missing the line ```--skip-validation \```. Added that and error disappeared.

Now I just have to get my VCFs into the right format for hail... 

By the way, would it be any help if I make a note of the tweaks to make the CentOS instructions work with Ubuntu?

**Comment by bw2** [comment]
Glad you're almost there, and yes your notes on Ubuntu would be great!
--skip-validation disables validation of  --genome-version and --sample-type values (eg. WES vs. WGS). Were you getting a validation error or was that code not working correctly?

Btw., I've got one more round of misc. updates to the install that I'm planning to PR later today. 
Will let you know in case you want to compare.

**Comment by jules-o** [comment]
OK I'll try to remember what I did :)

Strange! I was getting the same error as before - that the account I had created did not have storage.buckets.get access to seqr-reference-data. I had changed --genome-version to 38 and --sample-type to WGS, but everything else was the same. 

Cool, I'll be interested to see the updates.

**Comment by jules-o** [comment]
Tweaks for Ubuntu 18.04:

**Adjust ulimits settings first**
1. Edit ```/etc/systemd/user.conf```and uncomment (or add) the line:
```
DefaultLimitNOFILE=65536
```

2. Repeat for ```/etc/systemd/system.conf```

3. Edit ```/etc/pam.d/su``` and uncomment the line:
```
# session    required   pam_limits.so
```

4. REBOOT! (logging out and in again wasn't enough on my system)
&nbsp;

**Then follow CentOS script, except:**

1. Deployment scripts: If downloading rather than cloning deployment scripts, use
```
sudo apt install -y unzip python-dev
```
instead of yum with python-devel.

2. Python dependencies: Don't use sudo - doesn't work well with pip in Ubuntu. (Also fix typo of 2 lines joined - original says ```pip install -r deploy/deploy-requirements.txtsudo pip install -r seqr/seqr-${SEQR_BRANCH}/deploy/deploy-requirements.txt```)
```
pip install -r <path_to_seqr>/deploy/deploy-requirements.txt
``` 

4. No need to download docker. The service is all included in minikube, better (for me) to save the disk space.

5. Kubectl & minikube: I already had these installed so not checked the instructions in the script - will need changing to apt with the relevant versions.

6. Install java: change to
```
sudo apt update
sudo apt install openjdk-11-jdk
```

7. Adjust system settings for elasticsearch: add extra line so now
```
echo '
* hard	 nofile	65536
* soft	 nofile	65536
elasticsearch  nofile  65536
' | sudo tee -a /etc/security/limits.conf
```
Hope all that makes sense!

**Comment by jules-o** [comment]
Damn, loading sample project not working after all (sorry!).
It was still running when I wrote before, went for a few hours then 
```
2018-09-06 05:26:03,068 INFO     Hail version: 0.1-408f188
2018-09-06 05:26:03,069 INFO     Error summary: EsHadoopException: Could not write all entries for bulk operation [10/10]. Error sample (first [5] error messages):
2018-09-06 05:26:03,069 INFO     	[variant][1-1149316-C-G]: document missing
2018-09-06 05:26:03,069 INFO     	[variant][1-1149480-G-A]: document missing
2018-09-06 05:26:03,070 INFO     	[variant][1-1153113-G-A]: document missing
2018-09-06 05:26:03,070 INFO     	[variant][1-1158631-A-G]: document missing
2018-09-06 05:26:03,070 INFO     	[variant][1-1158675-CCTT-C]: document missing
2018-09-06 05:26:03,070 INFO     Bailing out...
```
(more logs attached in case it's relevant)
[load-example-data_log.txt](https://github.com/macarthur-lab/seqr/files/2356969/load-example-data_log.txt)

**Comment by bw2** [comment]
Thanks for the logs. 
Did you by chance restart the pipeline from the middle?
These errors can happen if the restart happens after the date rolls over because it computes the index name from scratch using the current date. 
There pipeline has an --index arg that can be used to override the index name.

**Comment by bw2** [comment]
yeah, spark attempts to use all CPUs and a lot of memory - especially if it's running VEP, so it does tend to take over a machine during some phases of loading.

Thanks for the Unbutu notes. I'll try creating an Ubuntu version of the install script. 
So far I've fixed the pip typo, and am working on other updates to the install which you should probably ignore - except that I increased max memory on elasticsearch to 5Gb
https://github.com/macarthur-lab/seqr/commit/548b300a1eaecbb1271b90a29e56df7a473482b8#diff-20c4fb26edb35ee153cf2087ac78199fL99

and also modified the minikube start command line for next time you decide to destroy/recreate your minikube instance:
https://github.com/macarthur-lab/seqr/commit/548b300a1eaecbb1271b90a29e56df7a473482b8#diff-20c4fb26edb35ee153cf2087ac78199fL53

**Comment by jules-o** [comment]
OK I got fed up with not being able to use my computer, decided to start completely from scratch again, this time following the suggested use with docker and ```--vm-driver=none``` to see if it's any more efficient than VirtualBox. Thought while I'm at it I might as well do a full Ubuntu 18.04 install script in case that saves you 5 mins - attached. 

It ran through smoothly on my machine but something else needs doing because seqr pod stalls with ```is_ready status = false```. From the logs I think it's a networking problem, presumably linked to either the ```vm-driver=none``` or some docker variable, as it can't seem to connect to any external ip addresses.

It's way past my bedtime so I shall have to leave it for now, but if you've got any bright ideas let me know. Else I'll try tomorrow, or just go back to VirtualBox.

[install_minikube_ubuntu_18.04.txt](https://github.com/macarthur-lab/seqr/files/2359086/install_minikube_ubuntu_18.04.txt)

**Comment by bw2** [comment]
Thanks for working through this with me. 
I'm looking into putting up pre-built images on Dockerhub to speed up the (re)install, and testing the end-to-end deployment on Ubuntu. 
Just to double check, when your computer was getting bogged do you remember which tasks were primarily consuming resources?

**Comment by jules-o** [comment]
Not sure I can be much use but happy to try. I think pre-built docker images would be very helpful. There must be more and more of us now coming from the medical side without a friendly bioinformatician to hand.

It was the load-example-project that kept going slow, especially later into the run. It helped to reboot then leave it running overnight with nothing else open - but that was when it bailed out and I haven't got as far as trying it again. Perhaps increasing java heap size would help.

I get the feeling this network problem is probably something simple, I just haven't worked out what yet.

**Comment by jules-o** [comment]
Did you ever get the end-to-end deployment working on Ubuntu? I couldn't get it to work with either ```--vm-driver=none``` or kvm2, so went back to VirtualBox - but still can't load example project. It starts OK, runs a couple of hours then freezes the whole computer. That's without using any other apps at all either before or during. I can't find any logs to suggest what the problem is. The last line before freeze was
```
INFO: org.apache.parquet.hadoop.ColumnChunkPageWriteStore: written 39B for [annotations, vep, motif_featurr_consequences, list, element, impact] BINARY: 116 values, 14B raw, 16B comp, 1 pages, encodings: [RLE, PLAIN]
```
Could it be simply that my computer isn't powerful enough? It's a ThinkPad T450s dual core Intel i7-5600U CPU @ 2.60GHz, dual boot, with 160GB disk space on the linux home partition and 20GB RAM. I allocated 100GB storage and 12GB memory to the minikube VM.

**Comment by bw2** [comment]
Hi Jules,  yes, I've been testing with --vm-driver=none on Ubuntu (and CentOS) and your hardware should be sufficient after the https://github.com/macarthur-lab/seqr/tree/linux-install-improvements branch gets merged. One new thing on that branch is `--cpu-limit` when loading the example data so you can stop it from running 8 VEP instances in parallel (which was the main thing that led to system overload and crashes). It also pulls pre-built images from a docker registry instead of building all images from scratch. I'm hoping to get this merged later this week and will let you know as soon as it's in.

**Comment by jules-o** [comment]
Ah brilliant, thank you. I don't mind it taking a while to run, can always leave overnight - just as long as it gets there eventually!

**Comment by bw2** [comment]
Hi Jules, I've now tested it several times on Ubuntu 4CPU/15Gb RAM nodes and deploy-all is working consistently with the updated the Install instructions at https://github.com/macarthur-lab/seqr#install

I split the install into 4 commands - the 1st one is OS-specific and installs general dependencies. steps 2 and 3 start elasticsearch and minikube, and step 4 runs the deploy-all command which now uses public docker images from https://console.cloud.google.com/gcr/images/seqr-project/GLOBAL
and loads reference data. Loading the example project is a separate optional step, but it works and shouldn't overload your machine as long as you give elasticsearch ~4Gb of RAM (the default in step2) and run with --cpu-limit=1 (the default in step4) and don't have other memory-heavy applications running. With 1 CPU, load-example-project should take ~20 hours.
Would be curious to hear how it goes if you have a chance to try it.

**Comment by jules-o** [comment]
Hi bw2, Thank you that's brilliant. Steps 1-3 were fine but step 4 crashes while deploying seqr: command terminated with exit code 137. Traceback:
```
  File "./servctl", line 280, in <module>
    deploy(args.deployment_target, components=deployable_components, runtime_settings=runtime_settings)
  File "/home/flutabex/seqr/deploy/utils/deploy_utils.py", line 136, in deploy
    deploy_seqr(settings)
  File "/home/flutabex/seqr/deploy/utils/deploy_utils.py", line 470, in deploy_seqr
    run_in_pod(postgres_pod_name, "/root/restore_database_backup.sh postgres seqrdb /root/$(basename %(restore_seqr_db_from_backup)s)" % locals(), verbose=True)
  File "/home/flutabex/seqr/deploy/utils/kubectl_utils.py", line 133, in run_in_pod
    run("kubectl exec %(it_arg)s %(full_pod_name)s -- %(command)s" % locals(), errors_to_ignore=errors_to_ignore, print_command=print_command, verbose=verbose, is_interactive=is_interactive)
  File "/home/flutabex/seqr/seqr/utils/shell_utils.py", line 98, in run
    raise RuntimeError(output)
RuntimeError: + psql -U postgres postgres -c 'DROP DATABASE seqrdb'
Username: postgres
Database: seqrdb
Backup File: /root/gene_reference_data_backup.gz
DROP DATABASE
+ psql -U postgres postgres -c 'CREATE DATABASE seqrdb'
CREATE DATABASE
+ psql -U postgres seqrdb
++ gunzip -c /root/gene_reference_data_backup.gz
SET
SET
SET
(and so on)
```

Tried twice now but same both times, can't work out quite what the error is. Full log from start of Deploy Seqr attached. [seqr_error.txt](https://github.com/macarthur-lab/seqr/files/2426079/seqr_error.txt)

Isn't it quick with the public images!

**Comment by bw2** [comment]
Thanks, and thanks for the error logs. 
I've only seen commands die like this if they hit memory limits (or rarely network timeouts). I just raised the postgres memory limits in the kubernetes configs. If you want to try re-deploying just seqr, you could go to the dir that has the step1.*.sh script, and do 
```
cd seqr/
git pull
source activate_virtualenv.sh
./servctl deploy seqr -d --restore-seqr-db-from-backup gene_reference_data_backup.gz --docker-image-tag release_20180926 minikube
```
it should get through the reference data. 

If the same error happens, you could instead deploy seqr without the reference data file, and run an update command to get reference data from original sources:

```
./servctl deploy seqr -d --docker-image-tag release_20180926 minikube
Ctrl-C to stop printing the logs
./servctl shell seqr minikube   # opens a shell inside the seqr container
# then run one of these:
python manage.py update_all_reference_data --omim-key $OMIM_KEY
# or 
python manage.py update_all_reference_data --skip-omim
```

**Comment by jules-o** [comment]
Well it didn't like that at all! Same error, including when I tried starting again from scratch. When I follow either of the options to deploy seqr on its own I get:
```
2018-09-28 13:11:05,706 INFO     seqr is_running status = None
2018-09-28 13:11:05,706 INFO     waiting for "seqr" to exit Running status
2018-09-28 13:11:05,775 INFO     seqr is_running status = None
2018-09-28 13:11:05,776 INFO     ==> kubectl exec  postgres-78995f5878-kczdx -- psql -U postgres postgres -c 'drop database seqrdb'
2018-09-28 13:11:05,843 INFO     error: cannot exec into a container in a completed pod; current phase is Failed
Traceback (most recent call last):
  File "./servctl", line 280, in <module>
    deploy(args.deployment_target, components=deployable_components, runtime_settings=runtime_settings)
  File "/home/flutabex/seqr/deploy/utils/deploy_utils.py", line 136, in deploy
    deploy_seqr(settings)
  File "/home/flutabex/seqr/deploy/utils/deploy_utils.py", line 466, in deploy_seqr
    verbose=True,
  File "/home/flutabex/seqr/deploy/utils/kubectl_utils.py", line 133, in run_in_pod
    run("kubectl exec %(it_arg)s %(full_pod_name)s -- %(command)s" % locals(), errors_to_ignore=errors_to_ignore, print_command=print_command, verbose=verbose, is_interactive=is_interactive)
  File "/home/flutabex/seqr/seqr/utils/shell_utils.py", line 98, in run
    raise RuntimeError(output)
RuntimeError: error: cannot exec into a container in a completed pod; current phase is Failed
```
```kubectl get pods``` shows one evicted postgres pod and one that stays pending for quite some time before eventually running. Describing the evicted pod shows
```
Status:             Failed
Reason:             Evicted
Message:            The node was low on resource: ephemeral-storage. Container postgres-pod was using 2011824Ki, which exceeds its request of 0.
```
If I manually delete the evicted pod then I don't get the completed pod error - but then it simply terminates with exit code 137 again as before. Then ```kubectl get pods``` gives
```
NAME                        READY     STATUS    RESTARTS   AGE
mongo-847f8866b9-7jr5g      1/1       Running   0          17m
phenotips-c46c7588b-5lbmq   0/1       Evicted   0          3m
phenotips-c46c7588b-7z5mx   0/1       Evicted   0          3m
phenotips-c46c7588b-84gb2   0/1       Evicted   0          3m
phenotips-c46c7588b-8wc4l   0/1       Evicted   0          3m
phenotips-c46c7588b-czdqk   0/1       Pending   0          3m
phenotips-c46c7588b-f5tbx   0/1       Evicted   0          3m
phenotips-c46c7588b-hh7rn   0/1       Evicted   0          3m
phenotips-c46c7588b-j6zq9   0/1       Evicted   0          3m
phenotips-c46c7588b-kn5hx   0/1       Evicted   0          3m
phenotips-c46c7588b-lcv9r   0/1       Evicted   0          3m
phenotips-c46c7588b-lhkfp   0/1       Evicted   0          16m
phenotips-c46c7588b-n9jbx   0/1       Evicted   0          3m
phenotips-c46c7588b-rlqtg   0/1       Evicted   0          3m
phenotips-c46c7588b-swjrf   0/1       Evicted   0          3m
phenotips-c46c7588b-vq5hb   0/1       Evicted   0          3m
phenotips-c46c7588b-vxth2   0/1       Evicted   0          3m
phenotips-c46c7588b-wnxzz   0/1       Evicted   0          3m
phenotips-c46c7588b-wsdz6   0/1       Evicted   0          3m
postgres-78995f5878-5zcdb   0/1       Evicted   0          11m
postgres-78995f5878-89gsq   0/1       Pending   0          1m
redis-675468d585-gpzdq      1/1       Running   0          16m
```
Then after a while kubectl starts saying no resources found even though the pods are still there and ```minikube status``` says everything correctly configured. None of the fixes I can find online work, so the only option then seems to be to start again. I've tried a few times, including completely uninstalling everything in between. Do you think it's to do with the vm-driver none option?

**Comment by bw2** [comment]
ouch. This definitely looks like it's hitting memory limits. 
The install script step1 was starting minikube without a  --memory arg, so I just added it to make sure it sets aside 5Gb. I've been testing on n1-standard-4 (4 vCPUs, 15 GB memory) VMs on google cloud that don't have anything else running, and just confirmed that it's working there. 

I like vm-driver=none because it's less overhead, and also when I tried virtualbox I couldn't get it working on the google ubuntu16 image.  If you want to try it though, I just added a VM_DRIVER arg to the step1 script, though it'll probably need other changes to get --vm-driver=virtualbox to work well.

Either way, if it would help to troubleshoot together, perhaps we could do a skype call?

**Comment by jules-o** [comment]
That's really good of you, thank you! I'll have another play over the weekend then if I can't get it working are you free on Mon or Tues?

**Comment by jules-o** [comment]
It's working! In VirtualBox anyway. I've got a couple more ideas to try with vm-driver=none as that is markedly faster than VirtualBox, but at least I do now have a fully functional install of seqr with the example project loaded. Woohoo!

One more question: is seqr compatible with hail 0.2? I've been having trouble working out how to get my VCFs in a form that will work - my VCFv4.2 from GATK gives lots of STRUCT warnings then just hangs, while the one I most want to use (VCFv4.1 from LongRanger) throws up a HailException. Tim over at the hail forum thought best bet would be to run 0.2 locally/in cloud - but can the data then be used in seqr?

Thanks again for all your help, I really appreciate all the time and effort you put into this.

**Comment by bw2** [comment]
Nice!! That's great to hear.

The seqr data loading pipeline currently entirely on 0.1 and it'll probably be another couple months before it's fully ported to 0.2 along with the reference data files. 

Also, I just saw your thread on hail discuss. 
For the Struct warnings, it looks like VEP is including an unexpected "tsl" field in the output. The fix would be to add these to hail's VEP schema, but since hail continues running as is, I think it's fine to just ignore the warnings. 
The hanging/crash is harder to troubleshoot - does it happen on the VEP step? and is there any log output?

For the PL error on the LongRanger VCF, does the vcf header have this line with Number=G?

```
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
```

**Comment by jules-o** [comment]
That's the weird thing - it just stops after the Struct warnings. No error, no log output (that I can see) - it just hangs, then if I wait long enough eventually stops altogether and goes back to the bash prompt as if nothing ever happened. 

The other doesn't seem to have the FORMAT PL header. Would it work if I simply add that in or would that create more errors further down?

**Comment by bw2** [comment]
Hmm.. If you do `./servctl shell pipeline-runner minikube`  it should open a shell in the pipeline-runner container and then `ls /hail_*.log` should have more detailed hail logs.
If there's nothing there, the only thing I can think of is that VEP or hail are running out of memory on some variants and getting killed.  This is a long shot, but if you add ` --vep-block-size 10` to the ./servctl load-dataset command, it'll reduce the number of variants hail passes to VEP at a time and might avoid the crash.

For the LongRanger VCF, could you share an example variant row? 

If column 9 looks like ```GT:AD:DP:GQ:PL```  then adding these to the header may fix that PL error
```
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
```
IIRC hail and other tools (like `vt decompose`) use these headers when splitting multi-allelic variants to decide how to split INFO and Genotype fields.

**Comment by jules-o** [comment]
Oh good grief... minikube started playing silly wotsits again, couldn't run commands from terminal, kubectl saying no resources found etc. Have had to do minikube delete and start again. Now have to get everything running again to test, meantime:

Sample variant row from LongRanger
```
chr1    10028   .       C       CA      0.00834598      10X_QUAL_FILTER;10X_RESCUED_MOLECULE_HIGH_DIVERSITY;10X_ALLELE_FRACTION_FILTER  NS=1;DP=5;DPB=6;AC=1;AN=2;AF=0.5;RO=155;AO=5;PRO=0;PAO=0;QR=112;QA=82;PQR=0;PQA=0;SRF=2;SRR=1;SAF=2;SAR=0;SRP=3.73412;SAP=7.35324;AB=0;ABP=0;RUN=1;RPP=7.35324;RPPR=9.52472;RPL=0;RPR=2;EPP=7.35324;EPPR=3.73412;DPRA=0;ODDS=6.25357;GTI=0;TYPE=ins;CIGAR=1M1I1M;NUMALT=1;MEANALT=1;LEN=1;MQM=60;MQMR=60;PAIRED=1;PAIREDR=1;technology.ILLUMINA=1;VCFALLELICPRIMITIVE;POSTHPC=1;POSTHPB=C;MUMAP_REF=17.5156;MUMAP_ALT=18;MMD=3.13324;RESCUED=116;NOT_RESCUED=510;POSTDNB=CT;POSTDNC=1;POSTTNB=CTA;POSTTNC=1;HAPLOCALLED=1       GT:PS:PQ:JQ:BX:GL       0|1:1:25:25:CATTATCAGGTTAGTA-1_45;TAAGTGCAGCCACTAT-1_45;ACCATTTGTTCTTTGT-1_45;CGAAGAGAGATAGCAT-1_45;CCTAGTCCAAAGGTTA-1_45;GTCTACCGTGAGTTAA-1_45;TGGTAGTTCCCTAACC-1_45;GAGTCCGGTCGTAGCC-1_45;TGTGGGCTCCTCTGCA-1_45;TACTCCGTCACCGCAG-1_45;CTCGATCTCCCTAACC-1_45;CCAACTCGTTCTCCCA-1_45;CTGATAGAGTTGGCAG-1_45;TATTACCCATCCTGGG-1_45;GAAGACGGTGACAATA-1_45;GGAAGCAGTCTGTAAC-1_45;AGGAGACGTTGTTGTG-1_45;TGAAAGAAGTTAGCGG-1_45;TGAAGGGAGATGAGAG-1_45;TTTGGTTGTTTCCTGC-1_45;AAACGGGAGACTACAA-1_45;AAGAAGTGTACAGCGA-1_45;TTTGTGTAGGGCGTTA-1_45;ACTGTAGCATGGGCCT-1_45;ACATACGTCAATAGGA-1_45;GAGCCGTAGCCACGCT-1_45;AACTGGTTCCAGCGAC-1_45;TAGTTGGTCCTAATGG-1_45;GCCGACAAGTATGAGT-1_45;TATCAGGCATCACGTA-1_45;TGTATTCCAACGACAG-1_45;ACTAAGCAGCGTTAAA-1_45;AACCATGGTTGTCGAT-1_45;ACGTACAAGAGTACCG-1_45;AAGGCAGAGGATACGC-1_45;AGTACCACAGAGCTCC-1_45;TCATTTGCATCGGTTA-1_45;GTCGTGGGTCTTAGCA-1_45;AAACACCAGAAGCCCA-1_45;ACTGAGTTCATTATCC-1_45;TAGTGGTCAACATCCA-1_45;CTCCGATGTGCGATAG-1_45;GCCATGGCACAGGCCT-1_45;TACACCCGTGAAGCCA-1_45_45;TACAGTGAGGCTGTAG-1_45;AGGGCAAGTCACCAGC-1_45;TGGATACAGTACGACG-1_45;AGGGAGTAGCAGTCTT-1_45;TGAGCTAGTGTTTGGT-1_45;ACGTACATCGTGTGGC-1_45;ACGTGCGAGCGGATCA-1_45;TACACCCGTTAGTGAA-1_45_45;CCAGGGTAGGTCGGAT-1_45;AGACCATTCAGGTGAG-1_45;GCCAGGTCAACCTCAA-1_45;GTCTCGTTCCATGCGG-1_45;GCCTCTAAGGAGCGGA-1_45;TACTTGTGTGTGAAAT-1_45;TGTACGAGTCTAGCGC-1_45;AGTGGCCCATGGATGG-1_45;TGAGAGGGTCAGAATA-1_45;AAAGAACTCCCTAACC-1_45;ACGCTCTCAGCTTGAT-1_45;AGGAGACTCTAAGCCA-1_45;CACATTTGTACAAGAT-1_45;ATCAGCAAGTGAACAT-1_45;ACGTATGTCCTCCTAG-1_45;AGTATCGCAGGTGAAC-1_45;CGTATGAAGAGCAATT-1_45;CGTCGTTTCGTTAGGT-1_45;CTATTTGAGCGTCGAA-1_45;CACGACGAGAGGTCTG-1_45;TCACGCTCAAGCCGCT-1_45;CTTCTCTTCTATGTGG-1_45;CAAGATCTCACGTAGT-1_45;ACAGCCGAGGTCAGAC-1_45;CCTACCAAGGCTATCT-1_45;CCGCTATGTCTTTCGC-1_45;CATTACTCATATGCTG-1_45;GTTTCTAAGGTGATAT-1_45;CAAGCGCTCGGGTGAA-1_45;CAATCCCAGGCGACAT-1_45;GGGATGATCTATGTGG-1_45;AAGGCAGAGCGTGTCC-1_45;ACATGGTAGTCAAGGC-1_45;GTCTGAATCAACGCTA-1_45;CAGCAGCGTGTTGTTG-1_45;CATCGGGGTTGCTGAT-1_45;CGGAACCAGCTACAAA-1_45;TACAGTGTCAACGGCC-1_45;TCTTTCCTCGCCCTAT-1_45;TTGTTTGGTGTGCGTC-1_45;CATATGGAGAGGGCTT-1_45;AGTCGATGTCTAGCCG-1_45;TACACCCCAATGGACG-1_45;ATCTTACAGGACATCG-1_45;CAAGTTGTCAGAGTAA-1_45;GCCGTGATCCATTTGT-1_45;GTGTGCGTCACTGTTT-1_45;CTTGGAAGTCACTGGC-1_45;CGGGCATTCGAAGCTT-1_45;CAAAGCTGTGGACGAT-1_45;CCGTTCAAGCTCTCGG-1_45;GGTACATCATATGAGA-1_45;GACACATTCTCATTCA-1_45;TGAGCCGAGTGTGAAT-1_45;TAAGAGAGTCCATGAT-1_45;ACGATACTCTACCGAA-1_45;CGAGCACCACCATGAT-1_45;GATTCTTCACAAACAA-1_45;TAAAGCCCAATGGGCA-1_45;ATAGCGTCAGTAGTTC-1_45;CCATCACCATTGTGCA-1_45;TCTTACATCCGCCTTA-1_45;CGGTTAAGTGGCCTCA-1_45;ACATGGTCATTCACTT-1_45_45;CGTTGGGCATTAGCCA-1_45;GTACTCCGTTAGACCT-1_45;GGGACTCCACAGCCAC-1_45;GCATCTCTCCGTTCAC-1_45;CTTGGCTAGGGCACTA-1_45;CAGATCAGTATAGGCG-1_45;GCCGTTTAGAGGGTTC-1_45;AAGGTTCGTAGCGTGA-1_45;CACCAGGAGTATCTCG-1_45,GGGACTCCACAGCCAC-1_45;CATCGAATCAGAGGAC-1_45;TGCATAGGTCAAGCGA-1_45;ACAGCCGAGGTCAGAC-1_45:0,-430,-1500
```
So column 9 is GT:PS:PQ:JQ:BX:GL

**Comment by bw2** [comment]
I've seen that happen. Sometimes docker eats CPU for a while and then comes back. 
Actually `minikube logs -f` might also be helpful for some of this, including when a process gets killed. 

Thanks for the LongRanger example. I'm not seeing a PL field - was that PL error happening somewhere else?
The loading pipeline currently expects genotypes to have GT, GQ, AB and DP fields, so I'm thinking for LongRanger, I could modify it to use GT and set the other fields to null. What do you think?

**Comment by jules-o** [comment]
Sorry for silence... I'm coming to the conclusion that minikube really doesn't like me. Currently going round in circles trying to get things working again. 

Re the PL error: I noticed that too when I checked out column 9 as you suggested - there _is_ no PL field, yet I very definitely get
 ```
Error summary: HailException: invalid PL field `0,2510,18100': expected 6 values, but got 3.
``` 
Same again when I briefly had everything working couple days ago. Must be interpreting something else as PL? Full headers + 1st couple rows attached in case that helps. [LongRangerVCF.txt](https://github.com/macarthur-lab/seqr/files/2443086/LongRangerVCF.txt)

If you think setting other fields to null would work then that'd be great... if I finally reach a state where I can test it... (if you can hear screaming, that's me shouting at the computer).

**Comment by bw2** [comment]
hmm.. sorry to hear that. Perhaps we could try troubleshooting over skype this or next week?
In the mean time, thanks for the long-ranger VCF. I'll see if I can get it working.

**Comment by bw2** [comment]
Hi Jules, thanks .. I've fixed the socat install bug, but not yet the google sdk one.
Perhaps we set up a time next week to troubleshoot vm-driver=none or other approaches - could you message me at weisburd at broadinstiute.org?

**Comment by jules-o** [comment]
Thanks bw2. I sent email yesterday but not sure if it got through - let me know if it hasn't arrived.
